Repository max2023-4th-project-01/FE-Cokkiri-Market, pull requests merged in 2023-08, with the labels that each got.

#3 초기 환경 세팅
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .gitignore
  .prettierrc
  README.md
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/assets/camera.svg
  src/assets/check.svg
  src/assets/chevron-down.svg
  src/assets/chevron-left.svg
  src/assets/chevron-right.svg
  src/assets/chevron-up.svg
  src/assets/circle-x-filled.svg
  src/assets/dots.svg
  src/assets/exclamation-circle.svg
  src/assets/heart-filled.svg
  src/assets/heart.svg
  src/assets/home.svg
  src/assets/keyboard-show.svg
  src/assets/layout-grid.svg
  src/assets/map-pin-filled.svg
  src/assets/message-noti.svg
  src/assets/message.svg
  src/assets/news.svg
  src/assets/paperclip.svg
  src/assets/pencil.svg
  src/assets/photo.svg
  src/assets/plus.svg
  src/assets/react.svg
  src/assets/search.svg
  src/assets/send.svg
  src/assets/user-circle.svg
  src/assets/x.svg
  src/main.tsx
  src/styles/designSystem.ts
  src/styles/index.css
  src/styles/reset.css
  src/utils/style.ts
  src/vite-env.d.ts
  styled.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: chore

#5 초기 환경 세팅 수정
  .eslintrc.cjs
  index.html
  package-lock.json
  package.json
  public/kiwi.svg
  public/vite.svg
  src/App.tsx
  src/assets/react.svg
  src/styles/designSystem.ts
  src/styles/index.css
Labels: chore, design

#8 button component 구현
  src/App.tsx
  src/components/Button.tsx
  src/styles/designSystem.ts
Labels: feat, refactor

#13 button props type 수정
  src/App.tsx
  src/components/Button.tsx
Labels: fix

#11 icon component 구현
  generateIcons.js
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icon/camera.svg
  src/assets/icon/check.svg
  src/assets/icon/chevron-down.svg
  src/assets/icon/chevron-left.svg
  src/assets/icon/chevron-right.svg
  src/assets/icon/chevron-up.svg
  src/assets/icon/circle-x-filled.svg
  src/assets/icon/dots.svg
  src/assets/icon/exclamation-circle.svg
  src/assets/icon/heart-filled.svg
  src/assets/icon/heart.svg
  src/assets/icon/home.svg
  src/assets/icon/keyboard-show.svg
  src/assets/icon/layout-grid.svg
  src/assets/icon/map-pin-filled.svg
  src/assets/icon/message-noti.svg
  src/assets/icon/message.svg
  src/assets/icon/news.svg
  src/assets/icon/paperclip.svg
  src/assets/icon/pencil.svg
  src/assets/icon/photo.svg
  src/assets/icon/plus.svg
  src/assets/icon/search.svg
  src/assets/icon/send.svg
  src/assets/icon/user-circle.svg
  src/assets/icon/x.svg
  src/components/icon/Icon.tsx
  src/components/icon/icons.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: feat, chore

#9 Modal 컴포넌트 구현
  .eslintrc.cjs
  index.html
  public/elephant-bg.png
  public/elephant.svg
  public/kiwi.svg
  src/App.tsx
  src/components/Modal.tsx
  src/components/TestModalContent.tsx
  src/styles/reset.css
Labels: feat, refactor, chore, design

#17 badge component 구현
  src/App.tsx
  src/components/Badge.tsx
Labels: feat

#20 setting library 및 리팩토링
  .eslintrc.cjs
  generateIcons.js
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/components/icon/Icon.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/page/Auth.tsx
  src/page/Main.tsx
  src/page/Test.tsx
  src/store.ts
Labels: feat, refactor, chore

#21 login page ui 구현
  src/App.tsx
  src/page/Auth.tsx
  src/page/auth/AuthInput.tsx
  src/page/auth/MyAccount.tsx
  src/page/auth/SignUpPanel.tsx
Labels: feat, design

#25 Alert 컴포넌트 구현 및 버그 수정
  src/components/Alert.tsx
  src/components/Modal.tsx
  src/components/TestModalContent.tsx
  src/page/Test.tsx
  src/store.ts
Labels: fix, feat, refactor

#27 fix #26: Alert 확인 버튼 기능 추가 및 수정
  src/components/Alert.tsx
  src/components/TestModalContent.tsx
Labels: fix

#28 회원가입, 로그인, 내계정 페이지 기능 추가
  src/App.tsx
  src/assets/icon/octocat.svg
  src/components/ProfileButton.tsx
  src/components/icon/icons.ts
  src/mocks/authHandlers.ts
  src/mocks/handlers.ts
  src/page/auth/LoginPage.tsx
  src/page/auth/MyAccount.tsx
  src/page/auth/MyProfilePage.tsx
  src/page/auth/SignUpPanel.tsx
  src/stores/authStore.ts
  src/utils/localStorage.ts
Labels: feat, refactor

#30 product item UI 및 util 함수 추가
  src/components/ProductItem.tsx
  src/mocks/handlers.ts
  src/mocks/mainHandlers.ts
  src/page/Test.tsx
  src/utils/addCommasToNumber.ts
  src/utils/getElapsedSince.ts
Labels: feat, design

#31 refactor #29 : api 변경에 맞게 수정
  src/components/ProductItem.tsx
  src/mocks/mainHandlers.ts
  src/page/Test.tsx
Labels: refactor

#33 refactor #32 : api 관리 폴더로 분할
  src/api/endPoint.ts
  src/api/fetcher.ts
  src/page/Test.tsx
Labels: refactor, chore

#35 동네 설정 모달 기능 구현 및 React-Query, Axios 적용
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/api/axios.ts
  src/api/endPoint.ts
  src/api/fetcher.ts
  src/components/Footer.tsx
  src/components/Layout.tsx
  src/components/LocationButton.tsx
  src/components/TestModalContent.tsx
  src/components/icon/Icon.tsx
  src/components/modal/AddLocation.tsx
  src/components/modal/LocationModal.tsx
  src/components/modal/Modal.tsx
  src/components/modal/SetLocation.tsx
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/locationHandlers.ts
  src/page/Test.tsx
  src/page/auth/LoginPage.tsx
  src/page/auth/MyAccount.tsx
  src/page/auth/MyProfilePage.tsx
  src/stores/useAuthStore.ts
  src/stores/useLocationStore.ts
  src/types.ts
Labels: feat, refactor, chore

#37 home page, category page 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/endPoint.ts
  src/api/fetcher.ts
  src/mocks/faker.ts
  src/mocks/handlers.ts
  src/mocks/mainHandlers.ts
  src/page/Main.tsx
  src/page/Test.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
Labels: feat, design

#42 rename #41 : 폴더 관심사 분리 및 불필요한 파일 삭제
  src/components/Modal.tsx
  src/components/locations/AddLocation.tsx
  src/components/locations/LocationButton.tsx
  src/components/locations/LocationModal.tsx
  src/components/locations/SetLocation.tsx
  src/page/Test.tsx
  src/page/auth/MyProfilePage.tsx
  src/page/auth/ProfileButton.tsx
  src/page/auth/SignUpPanel.tsx
  src/store.ts
Labels: rename

#45 device에 맞는 크기 결정
  src/App.tsx
  src/components/Layout.tsx
  src/components/Modal.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/stores/useScreenConfigStore.ts
  src/styles/reset.css
Labels: feat, refactor, design
