Repository max2023-4th-project-01/FE-Cokkiri-Market, pull requests merged in 2023-09, with the labels that each got.

#48 header component 구현
  src/components/Header.tsx
  src/page/auth/MyAccount.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
Labels: feat, refactor

#50 로그인/회원가입 요청 API 명세서랑 다른 부분 수정
  src/api/endPoint.ts
  src/mocks/authHandlers.ts
  src/page/auth/LoginPage.tsx
  src/page/auth/SignUpPanel.tsx
Labels: fix

#52 npm script 추가
  package-lock.json
  package.json
Labels: chore

#55 사소한 refactoring
  src/App.tsx
  src/components/Error.tsx
  src/page/auth/MyProfilePage.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
  src/stores/useScreenConfigStore.ts
Labels: refactor

#56 동네검색 모달화면 무한스크롤 기능 구현
  package-lock.json
  package.json
  src/api/fetcher.ts
  src/components/locations/AddLocation.tsx
  src/mocks/authHandlers.ts
  src/mocks/locationHandlers.ts
  src/queries/useLocationQuery.ts
  src/types.ts
Labels: feat, refactor, chore

#58 button componenet 리팩토링
  src/components/Alert.tsx
  src/components/Button.tsx
  src/components/button/Button.tsx
  src/components/button/TextButton.tsx
  src/components/icon/Icon.tsx
  src/components/locations/LocationButton.tsx
  src/components/locations/LocationModal.tsx
  src/components/locations/SetLocation.tsx
  src/page/Test.tsx
  src/page/auth/LoginPage.tsx
  src/page/auth/MyProfilePage.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
Labels: refactor

#61 Dropdown 공통 컴포넌트 구현
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/ProductItem.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/MenuItem.tsx
  src/hooks/useScrollLock.ts
  src/page/home/Home.tsx
  src/styles/designSystem.ts
Labels: feat, design

#69 배포 전 피드백과 API 수정사항 반영 및 회원가입 시 위치 추가 기능 구현 PR
  src/api/authFetcher.ts
  src/api/axios.ts
  src/api/fetcher.ts
  src/api/locationFetcher.ts
  src/api/mainFetcher.ts
  src/assets/image/icon_accessories.png
  src/assets/image/icon_appliance.png
  src/assets/image/icon_baby.png
  src/assets/image/icon_beauty.png
  src/assets/image/icon_book.png
  src/assets/image/icon_car.png
  src/assets/image/icon_clothes.png
  src/assets/image/icon_digital.png
  src/assets/image/icon_etc.png
  src/assets/image/icon_food.png
  src/assets/image/icon_furniture.png
  src/assets/image/icon_hobby.png
  src/assets/image/icon_kitchen.png
  src/assets/image/icon_man.png
  src/assets/image/icon_pet.png
  src/assets/image/icon_plant.png
  src/assets/image/icon_sports.png
  src/assets/image/icon_ticket.png
  src/assets/image/index.ts
  src/components/Error.tsx
  src/components/Loader.tsx
  src/components/ProductItem.tsx
  src/components/locations/AddLocation.tsx
  src/components/locations/HomeLocationModal.tsx
  src/components/locations/SetLocation.tsx
  src/components/locations/SignUpLocationModal.tsx
  src/hooks/useDebounceValue.ts
  src/hooks/useScrollLock.ts
  src/main.tsx
  src/mocks/faker.ts
  src/mocks/locationHandlers.ts
  src/mocks/mainHandlers.ts
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
  src/queries/useItemQuery.ts
  src/queries/useLocationQuery.ts
  src/stores/useAuthStore.ts
  src/types.ts
Labels: fix, feat, refactor

#73 배포를 위한 리팩토링
  src/App.tsx
  src/api/axios.ts
  src/components/Loader.tsx
  src/page/auth/LoginPage.tsx
  src/page/auth/OAuthLoading.tsx
Labels: refactor

#75 판매 내역 페이지 구현
  src/App.tsx
  src/api/SellHistoryFetcher.ts
  src/api/axios.ts
  src/api/endPoint.ts
  src/api/mainFetcher.ts
  src/components/Badge.tsx
  src/components/Footer.tsx
  src/mocks/faker.ts
  src/mocks/handlers.ts
  src/mocks/itemsHandlers.ts
  src/page/SellHistory.tsx
  src/page/home/Home.tsx
  src/types.ts
Labels: feat, refactor

#77 관심 내역 페이지 구현
  src/App.tsx
  src/api/endPoint.ts
  src/api/mainFetcher.ts
  src/components/Footer.tsx
  src/mocks/itemsHandlers.ts
  src/page/FavoritesHistory.tsx
  src/queries/useItemQuery.ts
  src/types.ts
Labels: feat

#80 무한스크롤 기능 적용 및 기존 코드 리팩터링
  src/App.tsx
  src/api/SellHistoryFetcher.ts
  src/api/endPoint.ts
  src/api/itemFetcher.ts
  src/api/mainFetcher.ts
  src/api/queries/useItemQuery.ts
  src/api/queries/useLocationQuery.ts
  src/components/ProductItem.tsx
  src/components/locations/AddLocation.tsx
  src/components/locations/HomeLocationModal.tsx
  src/components/locations/LocationButton.tsx
  src/components/locations/SetLocation.tsx
  src/mocks/itemsHandlers.ts
  src/mocks/locationHandlers.ts
  src/page/Favorites.tsx
  src/page/SalesList.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
  src/queries/useItemQuery.ts
Labels: feat, refactor

#81 피드백 받은 로직 반영
  src/page/auth/LoginPage.tsx
  src/page/auth/SignUpPanel.tsx
Labels: refactor

#84 상품 상세페이지 구현 PR
  src/App.tsx
  src/api/fetchers/authFetcher.ts
  src/api/fetchers/itemDetailsFetcher.ts
  src/api/fetchers/itemFetcher.ts
  src/api/fetchers/locationFetcher.ts
  src/api/queries/useItemDetailsQuery.ts
  src/api/queries/useItemQuery.ts
  src/api/queries/useLocationQuery.ts
  src/components/Badge.tsx
  src/components/Header.tsx
  src/components/ProductItem.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/MenuItem.tsx
  src/components/itemDetails/ImageSlider.tsx
  src/mocks/handlers.ts
  src/mocks/itemDetailsHandlers.ts
  src/mocks/itemsHandlers.ts
  src/mocks/locationHandlers.ts
  src/page/ItemDetails.tsx
  src/page/Test.tsx
  src/page/auth/LoginPage.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
Labels: feat, design, rename

#83 product editor 구현
  src/api/endPoint.ts
  src/api/fetchers/itemDetailsFetcher.ts
  src/api/fetchers/itemFetcher.ts
  src/api/queries/useItemDetailsQuery.ts
  src/api/queries/useItemQuery.ts
  src/components/Layout.tsx
  src/components/ProductItem.tsx
  src/hooks/useInput.ts
  src/mocks/itemDetailsHandlers.ts
  src/mocks/itemsHandlers.ts
  src/page/ItemDetails.tsx
  src/page/home/Home.tsx
  src/page/productEditor/CategoryContainer.tsx
  src/page/productEditor/CategorySelectModal.tsx
  src/page/productEditor/LocationDropdown.tsx
  src/page/productEditor/PictureContainer.tsx
  src/page/productEditor/ProductContent.tsx
  src/page/productEditor/ProductEditorPanel.tsx
  src/stores/useProductEditorStore.ts
  src/types.ts
  tsconfig.json
Labels: feat, refactor, design

#87 기타 리팩토링
  src/api/queries/useItemQuery.ts
  src/page/Favorites.tsx
  src/page/auth/ProfileButton.tsx
  src/page/productEditor/CategoryContainer.tsx
  src/page/productEditor/PictureContainer.tsx
  src/types.ts
Labels: refactor

#88 4주차 PR전 피드백 반영 및 수정
  src/App.tsx
  src/api/axios.ts
  src/api/queries/useItemQuery.ts
  src/components/Footer.tsx
  src/components/ProductItem.tsx
  src/components/itemDetails/ImageSlider.tsx
  src/components/itemDetails/ItemDetailsSkeleton.tsx
  src/components/locations/AddLocation.tsx
  src/components/locations/HomeLocationModal.tsx
  src/components/locations/SignUpLocationModal.tsx
  src/page/Chatting.tsx
  src/page/ItemDetails.tsx
  src/page/auth/LoginPage.tsx
  src/page/auth/MyAccount.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/router/ProtectedRoute.tsx
Labels: fix, feat, refactor

#67 toast alert
  src/api/queries/useLocationQuery.ts
  src/assets/icon/error.svg
  src/assets/icon/success.svg
  src/assets/icon/warning.svg
  src/components/Layout.tsx
  src/components/ProductItem.tsx
  src/components/Toast.tsx
  src/components/icon/Icon.tsx
  src/components/icon/icons.ts
  src/mocks/authHandlers.ts
  src/page/Chatting.tsx
  src/page/ItemDetails.tsx
  src/page/auth/SignUpPanel.tsx
  src/router/ProtectedRoute.tsx
  src/stores/useToastStore.ts
Labels: feat

#91 프로젝트에 있는 버그 및 리팩토링
  src/page/Favorites.tsx
  src/page/auth/AuthInput.tsx
  src/page/auth/LoginPage.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/productEditor/PictureContainer.tsx
  src/page/productEditor/ProductEditorPanel.tsx
  src/stores/useScreenConfigStore.ts
Labels: fix, refactor

#93 이미지 슬라이더 리팩터링 및 개선하기
  src/components/itemDetails/ImageSlider.tsx
  src/components/itemDetails/Slide.tsx
  src/components/itemDetails/Slider.tsx
  src/page/ItemDetails.tsx
  src/page/auth/MyAccount.tsx
Labels: fix, feat

#95 토스트 리팩토링
  src/api/queries/useLocationQuery.ts
  src/components/Layout.tsx
  src/components/ProductItem.tsx
  src/components/Toast.tsx
  src/components/toast/Toast.tsx
  src/components/toast/ToastContainer.tsx
  src/main.tsx
  src/page/ItemDetails.tsx
  src/page/auth/SignUpPanel.tsx
  src/router/ProtectedRoute.tsx
  src/stores/useToastStore.ts
Labels: refactor

#97 사소한 수정 및 리팩토링
  src/api/fetchers/authFetcher.ts
  src/api/fetchers/itemFetcher.ts
  src/api/queries/useItemQuery.ts
  src/components/ProductItem.tsx
  src/mocks/faker.ts
  src/page/Favorites.tsx
  src/page/ItemDetails.tsx
  src/page/SalesList.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/Home.tsx
  src/page/productEditor/CategoryContainer.tsx
  src/page/productEditor/ProductEditorPanel.tsx
Labels: refactor

#99 미구현 기능 추가 및 리팩토링
  src/api/endPoint.ts
  src/api/fetchers/authFetcher.ts
  src/components/Header.tsx
  src/mocks/authHandlers.ts
  src/mocks/itemsHandlers.ts
  src/page/auth/MyAccount.tsx
  src/page/auth/MyProfilePage.tsx
  src/page/home/Home.tsx
  src/router/ProtectedRoute.tsx
  src/stores/useAuthStore.ts
Labels: feat, refactor

#100 4주차 피드백 받은 부분 리팩터링과 빠진 기능 수정
  src/api/fetchers/authFetcher.ts
  src/components/Alert.tsx
  src/components/Badge.tsx
  src/components/Header.tsx
  src/components/ProductItem.tsx
  src/components/dropdown/ProductItemDropdown.tsx
  src/components/dropdown/UserLocationDropdown.tsx
  src/components/toast/Toast.tsx
  src/page/ItemDetails.tsx
  src/page/SalesList.tsx
  src/page/auth/MyAccount.tsx
  src/page/auth/MyProfilePage.tsx
  src/page/home/Home.tsx
  src/page/productEditor/LocationDropdown.tsx
  src/router/ProtectedRoute.tsx
  src/utils/extractKeyName.ts
Labels: fix, feat, refactor

#101 드롭다운 아래 공간에 따라 열릴 방향 결정하는 기능 추가
  src/components/Layout.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/locations/SignUpLocationModal.tsx
  src/hooks/useGetDropdownDirection.ts
  src/page/ItemDetails.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/productEditor/ProductEditorPanel.tsx
  src/stores/useScreenConfigStore.ts
Labels: feat, refactor
