Repository max2023-4th-project-01/FE-Cokkiri-Market, pull requests merged in 2023-10, with the labels that each got.

#103 채팅 관련 ui구현
  src/App.tsx
  src/api/endPoint.ts
  src/api/fetchers/chatFetcher.ts
  src/api/queries/useChatQuery.ts
  src/components/Layout.tsx
  src/components/SlidePanel.tsx
  src/mocks/chatHandlers.ts
  src/mocks/handlers.ts
  src/page/Chatting.tsx
  src/page/chat/ChatRoom.tsx
  src/page/chat/ChattingItem.tsx
  src/page/chat/ChattingList.tsx
  src/page/chat/Message.tsx
  src/stores/usePanelStore.ts
Labels: feat, refactor, design

#106 사소한 버그 수정 및 리팩토링
  src/components/ProductItem.tsx
  src/mocks/chatHandlers.ts
  src/page/ItemDetails.tsx
  src/page/auth/LoginPage.tsx
  src/page/chat/ChatRoom.tsx
  src/page/chat/ChattingItem.tsx
  src/page/productEditor/ProductEditorPanel.tsx
  src/utils/addCommasToNumber.ts
  src/utils/priceToString.ts
Labels: fix, refactor

#107 소소한 버그 수정
  src/api/queries/useItemQuery.ts
  src/api/queries/useLocationQuery.ts
  src/components/locations/AddLocation.tsx
  src/page/Favorites.tsx
  src/page/SalesList.tsx
  src/page/home/Home.tsx
Labels: fix
